name: 'Launch Happy Path tests of Eclipse Che'
description: 'Start Happy Path tests of Eclipse Che'
runs:
  using: 'node12'
  main: 'lib/index.js'
inputs:
  che-url:
    description: 'Url of the Eclipse Che Server'
    required: true
  devfile-path:
    description: 'Path to the devfile to use for the workspace'
    required: false
